
server:
  port: 8761

spring:
  application:
    name: cluster-server

eureka:
  server:
    response-cache-update-interval-ms: 1000
    enable-self-preservation: true
    # eviction-interval-timer-in-ms: 1000
    max-elements-in-peer-replication-pool: 5000
  client:
    register-with-eureka: false # 자기 자신을 eureka 서버에 등록 할 것인지 여부
    fetch-registry: false # client 서비스가 eureka 서버로부터 서비스 리스트 정보를 local 에 캐싱 할껀지 여부
    service-url:
      defaultZone: http://localhost:8761/eureka # eureka 를 서비스 하기 위한 URL
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90